In [2]:
import numpy as np

speed = [99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86]

x = np.mean(speed)

print(x)

89.76923076923077


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [15]:
arr = np.array([1, 2, 3, 4, 5], ndmin = 2)
print(arr)

[[1 2 3 4 5]]


In [16]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

1


In [17]:
arr = np.array([1, 2, 3, 4 ,5])
print(arr[0])

1


In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[4])

50


In [21]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1][0])

50


In [22]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [3]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4])

[15 20 25]


In [4]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))


[3 2 5 1 4]


In [5]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 5 3 4 2]


In [1]:
from scipy import constants
print(constants.pi)

3.141592653589793


In [2]:
from scipy import constants
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

In [3]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn, 0)

print(myroot.x)

[-0.73908513]


In [4]:
from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2

myMin = minimize(eqn, 0, method='BFGS')

print(myMin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [5]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2
